#!/bin/bash
set -e

IMAGE="progrium/buildstep"

CMD="sudo add-apt-repository ppa:inkscape.dev/stable && sudo apt-get update && sudo apt-get install install && sudo apt-get clean"

ID=$(docker run -d $IMAGE /bin/sh -c "$CMD")
docker attach $ID
test $(docker wait $ID) -eq 0
docker commit $ID $IMAGE > /dev/null
