#!/bin/bash
set -e

IMAGE="progrium/buildstep"

CMD="add-apt-repository ppa:inkscape.dev/stable && apt-get update && apt-get install && apt-get clean"

ID=$(docker run -d $IMAGE /bin/sh -c "$CMD")
docker attach $ID
test $(docker wait $ID) -eq 0
docker commit $ID $IMAGE > /dev/null
