#!/usr/bin/env bash
echo "-----> Injecting Inkscape ..."

cat > inkscape && dpkg -s inkscape > /dev/null 2>&1 || (add-apt-repository ppa:inkscape.dev/stable && apt-get update && apt-get install inkscape && apt-get clean)"