#!/usr/bin/env bash
APP="$1"; IMAGE="dokku/$APP"

echo "-----> Injecting Inkscape ..."

set -e

CMD="cat > inkscape && \
   dpkg -s inkscape > /dev/null 2>&1 || \
   (apt-get update && apt-get install -y inkscape && apt-get clean)"

ID=$(docker run -i -a stdin $IMAGE /bin/bash -c "$CMD")
test $(docker wait $ID) -eq 0
docker commit $ID $IMAGE > /dev/null
